name: Self-Hosted Runner Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Determine changed files
      id: changed-files
      run: |
       if [ "${{ github.event_name }}" = "pull_request" ]; then
          git diff --name-only  > changed_files.txt
        fi

    - name: Run Tclint on changed files
      run: |
        while IFS= read -r file; do
          echo "$file"
          tclint "$file" --ignore "trailing-whitespace,spacing,indent,line-length,blank-lines"
        done < changed_files.txt
