name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug information
      run: |
        echo "Event name: ${{ github.event_name }}"
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "Pull request base ref: ${{ github.event.pull_request.base.ref }}"
          echo "Pull request head ref: ${{ github.event.pull_request.head.ref }}"
          echo "Pull request base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Pull request head SHA: ${{ github.event.pull_request.head.sha }}"
        else
          echo "Before SHA: ${{ github.event.before }}"
          echo "Current SHA: ${{ github.sha }}"
        fi

    - name: Determine changed files
      id: changed-files
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > changed_files.txt
        else
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
        fi

    - name: Run Tclint on changed files
      run: |
        while IFS= read -r file; do
          tclint "$file" --ignore "trailing-whitespace,spacing,indent,line-length,blank-lines"
        done < changed_files.txt
