name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run Tclint
      run: |
        output=$(tclint test.tcl --ignore "trailing-whitespace,spacing,indent,line-length,blank-lines")
        echo "Tclint output:"
        echo "$output"
        if [ -n "$output" ]; then
          echo "Tclint found issues."
          echo "$output"
          exit 1
        else
          echo "Tclint passed."
        fi
