name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Determine changed files
      id: changed-files
      run: |
       if [ "${{ github.event_name }}" = "pull_request" ]; then
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > changed_files.txt
        else
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
        fi

    - name: Run Tclint on changed files
      run: |
        while IFS= read -r file; do
          tclint "$file" --ignore "trailing-whitespace,spacing,indent,line-length,blank-lines"
        done < changed_files.txt
